{
 "title": "Examine Specific Quabo",
 "description": "Inspect a single Quabo's metadata.",
 "tags": [ "Quabo" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "quabo",
    "label": "Quabo ",
    "query": "SHOW MEASUREMENTS ON \"metadata\" WHERE \"observatory\" = '$observatory' "
   },
   {
    "name": "observatory",
    "label": "Observatory",
    "query": "SHOW TAG VALUES ON \"metadata\"  WITH KEY = \"observatory\""
   }
  ]
 },
 "panels": [
  {
   "title": "Hardware",
   "type": "stat",
   "description": "Information about $quabo's hardware.",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Board Loc",
     "query": "SELECT last(BOARDLOC) FROM \"$quabo\"  WHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping'"
    },
    {
     "alias": "Quabo version",
     "query": "SELECT last(PCBREV_N) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping'"
    }
   ]
  },
  {
   "title": "Status timeline",
   "type": "state-timeline",
   "description": "Status timeline of this Quabo's various statuses.\n\nNote that in a given module, only the Quabo at position 1 contains valid Shutter Status metadata. ",
   "gridPos": { "h": 7, "w": 9, "x": 2, "y": 0 },
   "targets": [
    {
     "alias": "Light Sensor",
     "query": "SELECT last(\"LIGHT_SENSOR_STATUS\") FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval)"
    },
    {
     "alias": "Shutter",
     "query": "SELECT last(\"SHUTTER_STATUS\") FROM \"$quabo\" WHERE  \"observatory\" = '$observatory' AND $timeFilter AND BOARDLOC%4=1 GROUP BY time($__interval) "
    },
    {
     "alias": "Start Up",
     "query": "SELECT last(\"StartUp\") FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter GROUP BY time($__interval)"
    },
    {
     "alias": "10 MHz Status",
     "query": "SELECT last(\"EXT_10MHz_STATUS\") FROM \"$quabo\" WHERE  \"observatory\" = '$observatory' AND $timeFilter AND BOARDLOC%4=0 GROUP BY time($__interval) "
    },
    {
     "alias": "1 PPS Status",
     "query": "SELECT last(\"EXT_1PPS_STATUS\") FROM \"$quabo\" WHERE  \"observatory\" = '$observatory' AND $timeFilter AND BOARDLOC%4=0 GROUP BY time($__interval) "
    }
   ]
  },
  {
   "title": "Detector Current Draw",
   "type": "timeseries",
   "description": "\"Detector x\"  plots the current drawn by detector array x.\n\nPlease see https://github.com/panoseti/panoseti/issues/149 for details about how this value is computed from the raw detector current measurement, HVIMONx",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "Detector 0",
     "query": "SELECT DETR0_CURR\nFROM \"$quabo\" \nWHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter "
    },
    {
     "alias": "Detector 1",
     "query": "SELECT DETR1_CURR\nFROM \"$quabo\" \nWHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter "
    },
    {
     "alias": "Detector 2",
     "query": "SELECT DETR2_CURR\nFROM \"$quabo\" \nWHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter "
    },
    {
     "alias": "Detector 3",
     "query": "SELECT DETR3_CURR\nFROM \"$quabo\" \nWHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter "
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "description": "Information about $quabo's firmware.",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Firmware version",
     "query": "SELECT last(FWVER) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping'"
    },
    {
     "alias": "FWTIME",
     "query": "SELECT last(FWTIME) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping'"
    }
   ]
  },
  {
   "title": "Status Log",
   "type": "logs",
   "description": "Record of status logs",
   "gridPos": { "h": 4, "w": 9, "x": 2, "y": 7 },
   "targets": [
    {
     "alias": "Status Log",
     "query": "SELECT last(\"AGG_STATUS_MSG\")\nFROM $quabo\nWHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter\nGROUP BY time($__interval), \"UID\" fill(null)"
    }
   ]
  },
  {
   "title": "UTC",
   "type": "stat",
   "description": "Last Computer_UTC",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(Computer_UTC) FROM $quabo WHERE \"observatory\"='$observatory' AND \"datatype\"='housekeeping' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Detector and FPGA Temperatures",
   "type": "timeseries",
   "description": "Detector temp is read from the TMP125 sensor, located at the center of the 4 detector arrays.",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Detector Temp",
     "query": "SELECT TEMP1 FROM $quabo WHERE \"observatory\"='$observatory' AND $timeFilter "
    },
    {
     "alias": "FPGA",
     "query": "SELECT TEMP2 FROM $quabo WHERE \"observatory\"='$observatory' AND $timeFilter "
    }
   ]
  },
  {
   "title": "Detector High Voltage Bias",
   "type": "timeseries",
   "description": "HVMONx is the bias voltage to detector array x. Note that negative values are plotted as positive.",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "HVMON0",
     "query": "SELECT -HVMON0 FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter "
    },
    {
     "alias": "HVMON1",
     "query": "SELECT -HVMON1 FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter "
    },
    {
     "alias": "HVMON2",
     "query": "SELECT -HVMON2 FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter"
    },
    {
     "alias": "HVMON3",
     "query": "SELECT -HVMON3 FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter "
    }
   ]
  },
  {
   "title": "VxMON",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "V12MON",
     "type": "timeseries",
     "description": "The voltage of the 1.2v supply to the FPGA MGT",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "V12MON",
       "query": "SELECT V12MON FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter "
      }
     ]
    },
    {
     "title": "V18MON",
     "type": "timeseries",
     "description": "The voltage of the 1.8v supply to the MAROCs",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "V18MON",
       "query": "SELECT V18MON FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter"
      }
     ]
    },
    {
     "title": "V33MON",
     "type": "timeseries",
     "description": "The voltage of the 3.3v supply to the MAROCs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "V33MON",
       "query": "SELECT V33MON FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter"
      }
     ]
    },
    {
     "title": "V37MON",
     "type": "timeseries",
     "description": "The voltage of the 3.7v switching supply",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "V37MON",
       "query": "SELECT V37MON FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter"
      }
     ]
    }
   ]
  },
  {
   "title": "IxMON",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "I10MON",
     "type": "timeseries",
     "description": "Current of the 1.0v supply to the FPGA core",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "alias": "I10MON",
       "query": "SELECT I10MON FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter "
      }
     ]
    },
    {
     "title": "I18MON",
     "type": "timeseries",
     "description": "Current of the 1.8v supply to the FPGA",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "alias": "I18MON",
       "query": "SELECT I18MON FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter "
      }
     ]
    },
    {
     "title": "I33MON",
     "type": "timeseries",
     "description": "Current of the 3.3v supply to the FPGA",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "amp" } },
     "targets": [
      {
       "alias": "I33MON",
       "query": "SELECT I33MON FROM \"$quabo\" WHERE \"observatory\" = '$observatory' AND $timeFilter"
      }
     ]
    }
   ]
  },
  {
   "title": "VCCx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "VCCAUX",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "VCCAUX",
       "query": "SELECT VCCAUX FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter"
      }
     ]
    },
    {
     "title": "VCCINT ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "volt" } },
     "targets": [
      {
       "alias": "VCCINT",
       "query": "SELECT VCCINT FROM $quabo WHERE \"observatory\" = '$observatory' AND $timeFilter "
      }
     ]
    }
   ]
  },
  {
   "title": "Miscellaneous Metadata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quabo UID",
     "type": "stat",
     "description": "$quabo's unique ID.",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "UID",
       "query": "SELECT last(UID) FROM \"$quabo\" WHERE \"observatory\" = '$observatory' "
      }
     ]
    }
   ]
  }
 ]
}