{
 "title": "Observatory Home",
 "description": "Display general status information about a PANOSETI observatory.",
 "tags": [
  "Overview",
  "Home"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "observatory",
    "label": "Observatory",
    "query": "SHOW TAG VALUES ON \"metadata\"  WITH KEY = \"observatory\""
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Quabo Status",
   "type": "stat",
   "description": "Last AGG_STATUS_MSG report from each Quabo.",
   "gridPos": { "h": 14, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"AGG_STATUS_LEVEL\")\nFROM /QUABO_.*/\nWHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter\nGROUP BY time($__interval), \"UID\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Detector Temperature Heat Map",
   "type": "heatmap",
   "description": "Heatmap of all Quabo TEMP1 metadata.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "alias": "TEMP1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "QUABO_1016",
     "query": "SELECT last(\"TEMP1\")\nFROM /QUABO_[\\d]*/\nWHERE \"observatory\"='$observatory' AND \"datatype\"='housekeeping' AND $timeFilter \nGROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "TEMP1" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Detector High-Voltage",
   "type": "timeseries",
   "description": "The plot shows (-1) x (bias voltage) for each of the 4 detector arrays on every active Quabo.",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "SELECT -last(HVMON0), -last(HVMON1), -last(HVMON2), -last(HVMON3)\nFROM /QUABO_.*/\nWHERE \"observatory\" = '$observatory' AND \"datatype\"='housekeeping' AND $timeFilter\nGROUP BY time($__interval)"
    }
   ]
  },
  {
   "title": "GPS Receiver Status",
   "type": "state-timeline",
   "description": "Timeline of GPS Status metadata.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 14 },
   "targets": [
    {
     "query": "SELECT last(RECEIVERMODE), last(GPSDECODINGSTATUS), last(DISCIPLININGMODE), last(DISCIPLININGACTIVITY)\nFROM GPSSUPP \nWHERE \"observatory\" = '$observatory' AND \"datatype\"='GPS' AND $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "WPS Status",
   "type": "state-timeline",
   "description": "Power strip status",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 14 },
   "targets": [
    {
     "alias": "$measurement",
     "query": "SELECT last(POWER)\nFROM /WPS(.*)/\nWHERE \"observatory\"='$observatory' AND \"datatype\"='outlet' AND $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "White Rabbit SoftPLL Status",
   "type": "state-timeline",
   "description": "Timeline of SOFTPLL status for each active WRS.",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 14 },
   "targets": [
    {
     "alias": "$measurement",
     "query": "SELECT last(\"SOFTPLL\")\nFROM /WRSWITCH.*/\nWHERE \"observatory\" = '$observatory' AND \"datatype\"='whiterabbit' AND $timeFilter\nGROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "10MHz and 1PPS Status",
   "type": "state-timeline",
   "description": "EXT_10MHz_STATUS and EXT_1PPS_STATUS from housekeeping packets.\nSee these docs for more info:\nhttps://github.com/panoseti/panoseti/wiki/Quabo-packet-interface#housekeeping-packet-64-bytes",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "alias": "$m $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "QUABO_1016",
     "query": "SELECT last(\"EXT_1PPS_STATUS\") as \"1PPS\" FROM /QUABO_\\d+/ WHERE  \"observatory\" = '$observatory' AND $timeFilter AND BOARDLOC%4=0  GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$m $col",
     "query": "SELECT last(\"EXT_10MHz_STATUS\") as \"10MHz\" FROM /QUABO_\\d+/ WHERE  \"observatory\" = '$observatory' AND $timeFilter AND BOARDLOC%4=0  GROUP BY time($__interval) "
    }
   ]
  }
 ]
}